;http://projecteuler.net/index.php?section=problems&id=2
;
; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
;

(def fib 
  (fn [n]
         (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2))))   
    ))

; (fib 34) == 3524578
; (fib 35) == 5702887, so (fib 34 is last required)

(reduce + (filter #(even? %) ( map #(fib %) (range 35))))
; 4613732